### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m1-evaluacion-intermedia-ClaBri#1]
Cool job @clarabrigido  !!!

Here you have some tips to improve the exercise:

## HTML
- [ ] Fix the language of the page
- [ ] Be extra careful with syntax, it looks like you have errors when closing the A tag of the image
- [ ] Menu items should be an unordered list
- [ ] Menu items should be clickable

## CSS - selectors
- [ ] Class selectors are free, let's use them instead tag selectors 
- [ ] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background color

## CSS - box model
- [ ] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;)

## CSS - other
- [ ] Avoid `BR` tags, we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [ ] Finish the main title styles: words should jump
- [ ] Fix color of links and main title size.

## Good practices
- [ ] Indent and avoid extra white spaces to improve readability and avoid bugs
- [ ] Try to improve your commit messages, better in English and using imperative
- [ ] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-g/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

## Final remarks

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margins, padding...
- add cosmetic styles: color, background color...

Then repeat the same with the main content.

Let me know if you have any doubts ;)

Go for it!!

**Comment by clarabrigido** [comment]
Hi Carlos!

Finished!

Let me know if you need somethings. 

Thanks!! :)

**Comment by clarabrigido** [comment]
Los cambios están en la rama hotfixes. Gracias!

**Comment by oneeyedman** [comment]
Hola, @clarabrigido, hay un scroll vertical que tiene pinta que sale por no tener la cabecera fija. Lo doy por válido para esta evaluación pero no cierro el issue para que tengas la obligación moral de solucionarlo

**Comment by clarabrigido** [comment]
Hola @oneeyedman ya lo he arreglado :) ¡Muchas gracias por avisarme!
